[package]
name = "svg_engine"
version.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
webrender_api = { workspace = true }
euclid = { workspace = true }
kurbo = { workspace = true }
lyon = { workspace = true }
log = { workspace = true }
svgtypes = "0.16"
usvg = { path = "D:/Projects/resvg/crates/usvg", features = ["shape-preservation"] }
